buildPlugin: set _MSPDBSRV_ENDPOINT_ on windows to a distinct value
This should fix random build failures for Windows, caused by `fatal error C1090: PDB API call failed, error code '23': (0x000006BA)`.